version: '3.8'

services:
  api_gateway:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file: .env 
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
      - rabbitmq

  db:
    image: postgres:13-alpine
    env_file: .env  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"] 

  parser_worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file: .env
    depends_on:
      - db
      - redis

  redis:  # No changes needed
    image: redis:6-alpine
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}  # Reference .env
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data: