services:
  - type: web
    name: file-parser
    env: python
    buildCommand: pip install -r requirements.txt && python -m flask db upgrade
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 4 app:create_app()
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: filedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
        